    agent:
        classname: ssnb.algos.td3.TD3
        config: ../../../configs/td3/td3_swimmer3.yaml

    params:
        architecture:
            min: 128
            max: 1024
        critic_optimizer_lr:
            min: 1e-4
            max: 1e-2

    study:
        n_trials: 100
        n_steps_per_trial: 250000
        n_sessions: 5
