    params:
        buffer_size:
            min: 1e5
            max: 1e6
        batch_size:
            min: 100
            max: 300
        tau_target:
            min: 0.005
            max: 0.05

    study:
      n_startup_trials: 1
      n_warmup_steps: 2
      n_trials: 5
      n_jobs: 1
      timeout: 900
