    agent:
        classname: ssnb.algos.TD3.TD3
        config: ../../../../configs/td3/td3_swimmer3.yaml

    params:
        buffer_size:
            min: 1e5
            max: 1e6
        batch_size:
            min: 100
            max: 300
        tau_target:
            min: 0.005
            max: 0.05
            type: float
            log: true

    study:
        n_startup_trials: 1
        n_warmup_steps: 2
        n_trials: 100
        n_jobs: 1
        timeout: 900

    trial:
        n_epochs: 350000
        n_epochs_per_session: 50000
