    agent:
        classname: ssnb.algos.TD3.TD3
        config: ../../../../configs/td3/td3_swimmer3.yaml

    params:
        buffer_size:
            min: 1e5
            max: 1e6
        batch_size:
            min: 100
            max: 300
        tau_target:
            min: 0.005
            max: 0.05
            type: float
            log: True

    study:
        n_trials: 100
        n_steps_per_trial: 200000
        n_sessions: 10
