    agent:
        classname: ssnb.algos.TD3.TD3
        config: ../../../../configs/td3/td3_swimmer3.yaml

    params:
        architecture:
            min: 4
            max: 12
        optimizer_lr:
            min: 1e-4
            max: 1e-2

    study:
        n_trials: 100
        n_steps_per_trial: 3000000
        n_sessions: 15
