    render_agents: False
    save_best: True

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./td3_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 2
      buffer_size: 1e6
      max_grad_norm: 0.5
      n_envs: 1
      n_steps: 1
      n_updates: 1
      batch_size: 100
      tau_target: 0.05
      eval_interval: 2500
      max_epochs: 990000
      discount_factor: 0.9999
      learning_starts: 10000
      policy: 'MlpPolicy'
      gradient_steps: 1
      nb_evals: 1
      action_noise: 0.1
      architecture:
        actor_hidden_size: [256, 256]
        critic_hidden_size: [256, 256]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Swimmer-v3
      xml_file: swimmer3.xml

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 5e-4

    critic_optimizer:
      classname: torch.optim.Adam
      lr: 2e-3
