    render_agents: False
    save_best: True

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./td3_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 3
      buffer_size: 10e6
      max_grad_norm: 0.5
      n_envs: 1
      n_steps: 200
      n_updates: 6
      batch_size: 200
      tau_target: 0.09
      eval_interval: 2500
      budget: 250000
      discount_factor: 1.0
      learning_starts: 10000
      nb_evals: 1
      action_noise: 0.1
      architecture:
        actor_hidden_size: [174, 174]
        critic_hidden_size: [253, 253]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Swimmer-v3
      xml_file: swimmer4.xml

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 0.0002

    critic_optimizer:
      classname: torch.optim.Adam
      lr: 0.0019172767244204265
